config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index, :edit, :update] do
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :text, presence: true, allow_blank: false
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable


  validates_length_of :text, maximum: 200, allow_blank: false
  validates_presence_of :lat, :long, message: "Unable to get your location"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable
  acts_as_voter
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :yakkarma, dependent: :destroy
  after_create :create_yakkarma

end

app/models/yakkarma.rb
class Yakkarma < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]
  before_action :set_post
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

    yakkarma = current_user.yakkarma
    yakkarma.amount += 1
    yakkarma.save
  end

  def destroy
    if @comment.user == current_user
      @comment.destroy

      yakkarma = current_user.yakkarma
      yakkarma.amount -= 1
      yakkarma.save
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order("created_at DESC")
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        yakkarma = current_user.yakkarma
        yakkarma.amount += 1
        yakkarma.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      yakkarma = current_user.yakkarma
      yakkarma.amount -= 1
      yakkarma.save
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:text, :lat, :long, :show_username)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  [<%= comment.created_at.strftime("%I:%M %p") %>]
  <%= comment.user.email %>
  <% if comment.user == current_user %>
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, remote: true, style: 'float: right' %>
  <% end %>
  <%= comment.text %>
  <hr />
</div>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_text').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <div class="container">
      <span class="alert-inner--icon"><i class="fas fa-info"></i></span>
      <span class="alert-inner--text"><%= notice %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
    <div class="container">
      <span class="alert-inner--icon"><i class="fas fa-times"></i></span>
      <span class="alert-inner--text"><%= alert %></span>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/_bottom_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand navbar-light bg-light fixed-bottom">
    <div class="navbar-collapse w-50 order-0">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    </div>
    <div class="mx-auto order-0">
      <a class="navbar-brand mx-auto" href="#">Navbar 2</a>
    </div>
    <div class="navbar-collapse w-50 order-0">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "<i class='far fa-plus-square'></i>".html_safe, new_post_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
</nav>
<% end %>

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light fixed-top">
  <% if !user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
      </li>
    </ul>
  <% else %>

  <div class="navbar-collapse w-100 order-0">
    <span class="navbar-text">
      <%= current_user.yakkarma.amount %>
    </span>
  </div>
  <div class="mx-auto order-0">
    <a class="navbar-brand mx-auto" href="#">Navbar 2</a>
  </div>
  <div class="navbar-collapse w-100 order-0">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "<i class='far fa-plus-square'></i>".html_safe, new_post_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yikyak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/top_navbar' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%= render 'layouts/bottom_navbar' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Lat</th>
      <th>Long</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.text %></td>
        <td><%= post.lat %></td>
        <td><%= post.long %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<script>
    $( document ).on('turbolinks:load', function() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(success, errorOut);
        } else {
            showError("Geolocation is not supported by this browser.");
        }

        function success(position) {
            //position.coords.latitude
            //position.coords.longitude
            $("#post_lat").val("123.456");
            $("#post_long").val("123.456");
        }

        function errorOut(error) {
            switch(error.code) {
                case error.PERMISSION_DENIED:
                    showError("User denied the request for Geolocation.");
                    break;
                case error.POSITION_UNAVAILABLE:
                    showError("Location information is unavailable.");
                    break;
                case error.TIMEOUT:
                    showError("The request to get user location timed out.");
                    break;
                case error.UNKNOWN_ERROR:
                    showError("An unknown error occurred.");
                    break;
            }
        }

        function showError(error) {
            $("body").prepend("<div class=\"alert alert-danger alert-dismissible fade show mb-0\" role=\"alert\">\n" +
                "    <div class=\"container\">\n" +
                "      <span class=\"alert-inner--icon\"><i class=\"fas fa-times\"></i></span>\n" +
                "      <span class=\"alert-inner--text\">" + error + "</span>\n" +
                "      <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">\n" +
                "        <span aria-hidden=\"true\">&times;</span>\n" +
                "      </button>\n" +
                "    </div>\n" +
                "  </div>");
            $("[name='commit']").prop('disabled', true);
        }

    });

    $("textarea#post_text").maxlength({
        showOnReady: false,
        alwaysShow: true,
        threshold: 0,
        warningClass: "small form-text text-muted",
        limitReachedClass: "small form-text text-danger",
        separator: " / ",
        preText: "",
        postText: "",
        showMaxLength: true,
        placement: "bottom-right-inside",
        message: null,
        showCharsTyped: true,
        validate: false,
        utf8: false,
        appendToParent: false,
        twoCharLinebreak: true,
        customMaxAttribute: null,
        allowOverMax: false
    });

</script>
  <%= form_with(model: @post, local: true, class: "container") do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.text_area :text, class: "form-control", maxlength: 200 %>
    </div>
    <%= form.hidden_field :lat %>
    <%= form.hidden_field :long %>
    <div class="form-check">
      <%= form.check_box :show_username, class: "form-check-input" %>
      <%= form.label :show_username %>
    </div>
    <%= form.submit class:"btn btn-primary" %>
  <% end %>

app/views/posts/show.html.erb
<script>
$("textarea#comment_text").maxlength({
showOnReady: false,
alwaysShow: true,
threshold: 0,
warningClass: "small form-text text-muted",
limitReachedClass: "small form-text text-danger",
separator: " / ",
preText: "",
postText: "",
showMaxLength: true,
placement: "bottom-right-inside",
message: null,
showCharsTyped: true,
validate: false,
utf8: false,
appendToParent: false,
twoCharLinebreak: true,
customMaxAttribute: null,
allowOverMax: false
});

</script>
<div class="container">
      <h1><%= @post.text %></h1>
      <% if @post.show_username? %>
        <%= @post.user.email %>
      <% end %>
      <hr>
  <div id="comment_pane">
      <% @comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
  </div>
    <div class="row fixed-bottom pb-5">
      <%= form_with(model: [@post, @comment], class: "container") do |form| %>
        <div class="input-group mb-3">
          <%= form.text_area :text, class: "form-control", maxlength: 200 %>
          <div class="input-group-append">
            <%= form.submit "test", class:"btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
</div>